### ISSUE TITLE
GWAS with different SNPs

### ISSUE THREAD

**Issue by holtzy** [YinLiLin/R-CMplot#2]
First of all, thanks for this nice package

I'm trying to output a stacked Manhattan plot with 3 GWAS summary statistics that have very few SNPs in common (`CMplot` function). It looks like only the SNPs that are **common** to the 3 dataset are plotted.

I am missing something? Or is it possible to improve the code to show all SNPs?

Thank you !

**Comment by YinLiLin** [comment]
Hi! holtzy,

Thanks very much for your using of CMplot! :rose:
Actually, CMplot could only visualize the data that share the common SNPs with different p-values. If there is a NA for the SNP, it would be deleted whatever it has p-value for other traits. 
So i suggest that after merge the 3 GWAS results, you could try to replace NAs with value 1 for the non-common SNPs, then plot it with CMplot.
Also i will update the codes to meet your problem. 
Hope it can solve your problem!

Thanks again!

Lilin

**Comment by holtzy** [comment]
Thanks for your answer and the hint!
Yan
