### ISSUE TITLE
Change diagonal color in QQ plot

### ISSUE THREAD

**Issue by sureman** [YinLiLin/R-CMplot#25]
Is there a way to change the diagonal color from red in the QQ plot?

Thanks, Brad

**Comment by YinLiLin** [comment]
Hi,

Thanks for your feedback.
I had removed this parameter at the current version as I thought it may not be that important. I will put it back at the next update of CMplot.

Regards,
LL

**Comment by YinLiLin** [comment]
Hi,

I have updated the code on GitHub, please source the online code to have a try.
If you want to change the colour of the diagonal of QQplot:
```r
CMplot(..., threshold.col="blue")
```
if you want to change the colour of the confidence interval of QQplot:
```r
CMplot(..., conf.int=T,conf.int.col="grey")
```
Those modifications will be updated in the next submission to CRAN.

Best,
LL

**Comment by sureman** [comment]
Thank you so much for your quick response and action and your very useful tool.

Regards, Brad
