### ISSUE TITLE
Plotting single chromosome

### ISSUE THREAD

**Issue by caultona** [YinLiLin/R-CMplot#32]
Hi,

Thanks for your excellent package.

When using the CRAN version I can plot a Manhattan plot for individual chromosomes using:

CMplot(dose[df$CHR==3,],plot.type="m",LOG10=TRUE, highlight.pch=19, file="jpg",memo="CHR3", threshold=c(1.27e-07, 2.18e-5),threshold.lty=c(1,2),threshold.lwd=c(1,2), threshold.col=c("red","blue"),amplify=FALSE,dpi=300,file.output=TRUE,verbose=TRUE)

however when I source the online code I run into the following error:

length of 'chr.labels' should equal to the number of chromosomes.

I would like to use the online code as I would like to use the highlight function to highlight a vector of SNP names, which does not seem to be available in the CRAN version.

Kind Regards,

Alex

**Comment by YinLiLin** [comment]
Hi Alex,

Thanks for pointing out this issue. It's a logical mistake in the source script, I have tweaked it just now, please source the online script and try again.

best,
Lilin

**Comment by caultona** [comment]
Great, that's working,

thank you for your fast response.

Cheers,
Alex
